### ISSUE TITLE
Make 4.4 build issue

### ISSUE THREAD

**Issue by jamesjer** [antoinemine/apron#56]
The Fedora Linux project is preparing to update GNU Make to version 4.4.  Apron 0.9.13 fails to build with this version of make, due to [this change](https://savannah.gnu.org/bugs/?57778).  The issue is that include directives for nonexistent files are no longer ignored, but are considered fatal errors.  The file `apron/Makefile` has such a directive on line 4: `include depend`.  On initially unpacking the archive, there is no file named `apron/depend`.  Furthermore, it cannot be created with `make -C apron depend`, because that reads the Makefile which wants to include the file named depend, which doesn't exist yet.

A workaround, which I will use for the Fedora build, is to do this before invoking make:
```
touch apron/depend
make -C apron depend
```

It would be better if the Makefile could be restructured to work with make 4.4 out of the box.

**Comment by antoinemine** [comment]
Thank you for reporting this. 

Could you tell me whether replacing `include depend` with `-include depend` or, alternatively, providing an empty `depend` file in the archive (similar to your fix I guess) would fix the problem?

**Comment by jamesjer** [comment]
Thanks for the fix!  Sorry for the silence.  My computer suffered a catastrophic motherboard failure, and I've been way behind on answering email since getting things put back together.

I tried building with this change.  At first it seemed to be working.  The build launched and compiled a number of files.  Ultimately, the build failed like this though:
```
In file included from ap_reducedproduct.c:14:
ap_global0.h:26:10: fatal error: ap_version.h: No such file or directory
   26 | #include "ap_version.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

There is no file named `depend` in the build directory.  So I tried running `make -C apron depend` first, before `make`.  That worked.

**Comment by antoinemine** [comment]
I've added a new small fix. The goal is to allow compiling with just `./configure; make`...
